//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>Комментарий</remarks>
public class Comment
{
	public virtual string Text
	{
		get;
		set;
	}

	public virtual DateTime CreateDate
	{
		get;
		set;
	}

	public virtual User CommentCreator
	{
		get;
		set;
	}

	public virtual User Addressee
	{
		get;
		set;
	}

}

