//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Новость
/// </summary>
public class News : Component, INews
{
	public virtual void GetAllAnnouncements()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetAnnouncement(Int Id)
	{
		throw new System.NotImplementedException();
	}

}

