//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Permission
{
	public virtual Role Role
	{
		get;
		set;
	}

	public virtual Action Action
	{
		get;
		set;
	}

	public virtual Component Component
	{
		get;
		set;
	}

}

