//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PlayerStatistics
{
	public virtual Int TotalGoals
	{
		get;
		set;
	}

	public virtual Int TotalGames
	{
		get;
		set;
	}

	public virtual Int TotalPasses
	{
		get;
		set;
	}

	public virtual Int TotalTrainings
	{
		get;
		set;
	}

	public virtual User User
	{
		get;
		set;
	}

}

