//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PlayerStatistics
{
	public virtual int TotalGoals
	{
		get;
		set;
	}

	public virtual int TotalGames
	{
		get;
		set;
	}

	public virtual int TotalPasses
	{
		get;
		set;
	}

	public virtual int TotalTrainings
	{
		get;
		set;
	}

	public virtual User User
	{
		get;
		set;
	}

}

