//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TrainingLocation
{
	public virtual object Coordinates
	{
		get;
		set;
	}

	public virtual object NearestMetro
	{
		get;
		set;
	}

	public virtual object Address
	{
		get;
		set;
	}

	public virtual object Name
	{
		get;
		set;
	}

}

