//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual string Password
	{
		get;
		set;
	}

	public virtual DateTime Birthday
	{
		get;
		set;
	}

	public virtual IEnumerable<Role> Roles
	{
		get;
		set;
	}

}

